# Setup
title:               Frank Taillandier
tagline:             Consultant web agile & UX
description:         J'aide les équipes à concevoir de bons produits
github:
  url: http://localhost:4000
baseurl:             ""
permalink:           pretty
excerpt_separator:   <!--more-->
paginate:            5

# About/contact
author:
  name: Frank Taillandier
  email: frank.taillandier@gmail.com
  twitter: DirtyF

analytics:
  google:
    tracking_id: UA-15560088-1

# SEO
logo: img/frank-taillandier.jpg
twitter:
  username: DirtyF
social:
  type: person
  links:
    - https://github.com/DirtyF
    - http://lanyrd.com/profile/dirtyf/
    - http://www.last.fm/user/DirtyF

kramdown:
  input: GFM

branch: gh-pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - Procfile
  - README.md
  - CNAME

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
