# Permalinks

permalink:           pretty

markdown: rdiscount
highlighter: pygments

# Setup
title:               Frank Taillandier
tagline:             Consultant web
description:         Help product owners and teams build useful quality web apps
url:                 http://frank.taillandier.me
paginate:            1
baseurl:             ""

sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Frank Taillandier
  url:               https://twitter.com/DirtyF
  email:             frank.taillandier@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
gems:
  - jekyll-sitemap
  - jekyll-feed

analytics:
  google:
    tracking_id: UA-58128258-1

social:
    twitter: dirtyf
