exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
gems:
  - jekyll-sitemap

site: Frank Taillandier
author: Frank Taillandier
description: Utopiste vélorutionnaire
markdown: rdiscount
highlighter: pygments

github: site.github

sass:
    style: compressed
